const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0Iyc3ZPeGhjdnM0bDBEeno2cndsd1ZKRGMxSUxXSzZ1WXVIWW5WWTYyYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiREdlNGRIVEdpb2l6Q0h0SFU3K3FYaC9aRW5nMlNLVUpkQXRvVkhQZEpXbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTTndYTnZkSVRKY3dYVG9TcVV6dVVRYVJhcjAwYkVLd1pIY1R4eVpQdVhzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIzWjkxaE54TVQ1Mk5XSHIxeVdaTXBWdUlYRFVicEd5QmsxcHUrdnJxOHpVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1IYmM5czl3OXpQMmo0QnFnRS83VXM0N2xoQ1NkaDVXbFJiMlIxanQvbUk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldaS1BIY2xkVzRsbWd5VTFPUHEzeHR4RHpRQlhoRWREOXp1eVltT1VUamc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMklwQVdlNVhCR29DTzZaMzdqdlYwS2RUc3RoK3dKamxZK05mQnNsc2JrMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidnFhZDRaWTIxVys2a0lNQW9zL1drN04wTGFHOFhkOUl6QW1PcDcwZVdXaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImE5SE15NEVGSnl4b3hBZHNoUzVJQ3pPTmUyQlVIWlI4dHJxdzZIMVMyTDdHUXFtM3Vubi9XYlRVd3lweTl4ZksxZFVPZko2UENneUdPTW5VWFZrK0NnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTY1LCJhZHZTZWNyZXRLZXkiOiJoYlhHemVlUkM2TDlLbTRsazM2ZnN3WFlCdEp3ODBBOCtkTC80RHJESnc4PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjUwOTM0ODU2MzQzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjlBRUY5OTIyNTQ3MkQ2MDFCRTMyODQ2QjZFOUYxOEM4In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDAyNDU2MjB9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6Ilk3VzdMV05SIiwibWUiOnsiaWQiOiI1MDkzNDg1NjM0MzoxM0BzLndoYXRzYXBwLm5ldCIsImxpZCI6IjI0MjAyMTc0MjY3ODAyMDoxM0BsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ092S3RyOEdFT0tVNkwwR0dBTWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IkhNVWJVYWVrLzhQMVhiVjN0bW0rVWlabm9HRVNIZVR4NW8xNklUMUoyM0U9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkFMcXdTSjFtNHBldUlqUXBVanRyQzJRMVVnOFRiWUFqVVJsV2JSNUMwV25BM3o0TG1aZlFKR2pXbklqYllSU3BRbXVYcC84QkJ5QW9Eam12cXJNTENBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJhUHZzeUk3VmM5NGRHd3RpSmFaR2V5eUVjNzIzZWV4QU9UNVIrMEdWZFNLSTY0aU1pSk5sMFZIS1VtYUErc0hUK205SjB3MitTL3N6WTc3MUVDWXBCdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjUwOTM0ODU2MzQzOjEzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlJ6RkcxR25wUC9EOVYyMWQ3WnB2bEltWjZCaEVoM2s4ZWFOZWlFOVNkdHgifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNCSUlEUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0MDI0NTYxNSwibGFzdFByb3BIYXNoIjoiMlAxWWhmIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNKy8ifQ==",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
